### ISSUE TITLE
Extracting `libv8_monolith-win-x64.lib.gz` without additional dependencies on Windows

### ISSUE THREAD

**Issue by RaisinTen** [just-js/v8#2]
Hello! Thanks a lot for building this project. 🙏 

I'm using this in a project on Windows. I wanted to extract `libv8_monolith-win-x64.lib.gz` using the built-in `tar` command ([it is natively available on Windows](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows)) but I get this error:

```cmd
> tar -xzvf libv8_monolith-win-x64.lib.gz
tar: Removing leading '/' from member names
x .: Can't remove already-existing dir: Permission denied
x .: Can't remove already-existing dir: Permission denied
tar: Invalid string table
tar: Error exit delayed from previous errors.
```

Any thoughts on how to fix this error? I was wondering if we could use `tar` to create the file in https://github.com/just-js/v8/blob/f575d181b6f3f6e0296cda5a1da8567510479814/.github/workflows/main.yml#L251, just like how the include headers are compressed in https://github.com/just-js/v8/blob/f575d181b6f3f6e0296cda5a1da8567510479814/.github/workflows/main.yml#L42, which can be extracted using `tar` without errors.

Or perhaps the `gzip` step could be removed? WDYT?

**Comment by billywhizz** [comment]
hi. it is just a single gzipped file, so to extract it run

```
gunzip libv8_monolith-win-x64.lib.gz
```

i should probably change that to use zip/unzip for windows as gunzip won't be common there.

**Comment by RaisinTen** [comment]
Windows doesn't seem to contain the `zip` or `gunzip` binaries by default, so it would require installing those dependencies unfortunately. :/

**Comment by paulocoghi** [comment]
@RaisinTen A simple solution would be to install 7zip, from https://7-zip.org

**Comment by RaisinTen** [comment]
I'm using 7zip currently as a workaround and the extraction works without errors, but I was hoping to be able to extract it without installing additional dependencies.

**Comment by billywhizz** [comment]
> I'm using 7zip currently as a workaround and the extraction works without errors, but I was hoping to be able to extract it without installing additional dependencies.

@RaisinTen can you try the zip file from [here](https://github.com/just-js/v8/actions/runs/7262845303) on windows? i have made the change and will use this going forward. should have 12.1 v8 release out in next couple of days.

**Comment by billywhizz** [comment]
you should be able to extract a zip on windows 10+ using powershell. https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.4

**Comment by RaisinTen** [comment]
@billywhizz that works like a charm. Thank you so much! :D
